# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
