# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
